const translations = {
  en: {
    company: "PRODUCT DESIGNER",
    main_title_1: "Transforming complexity into simplicity and",
    main_title_2: "intuitiveness.",
    main_description: "For the past 4 years, I've been creating experiences that solve real problems with strategy and purpose. From discovery to delivery, I'm passionate about being part of every step of the process — understanding people, mapping needs, and turning all of that into thoughtful solutions.",
    talk_to_me: "Talk to me",
    resume: "Resume",
    about_me_title: "You can call me Gei",
    about_me_subtitle: "I'm Product Designer",
    about_me_paragraph_1: "With 4 years of experience in UX/UI Design, I work on end-to-end solutions for B2B and B2C products — from research to high-fidelity prototyping. I use Figma daily to create and iterate on intuitive interfaces, always aligned with business goals.",
    about_me_paragraph_2: "My background in Psychology led me to discover design as a way to solve real problems through technology — and that’s what drives me. In my free time, I enjoy discovering new places, having relaxed meetups with friends, and good conversations without any rush.",
    about_me_psychology: "PSYCHOLOGY",
    about_me_human_first: "Human-first",
    about_me_trips: "TRIPS",
    about_me_footer: "Building solutions",
    project_title: "FluencyForge",
    project_tag_mobile: "Mobile",
    project_tag_teaching: "Teaching",
    project_description: "App focused on education and learning new languages. Explore the boundaries of linguistic fluency with FluencyForge: where personalization meets efficiency, shaping your path to language mastery.",
    project_card_screens_amount: "+50",
    project_card_components_amount: "+20",
    project_card_other_amount: "+20",
    project_card_screens: "Screens",
    project_card_components: "Components",
    project_card_other: "Other",
    project_skills_title: "Applied skills",
    project_skills_1: "Design thinking | Competitor analysis | Quantitative research",
    project_skills_2: "Qualitative research | Prototyping | Wireframe | User flow",
    project_skills_3: "Information architecture | Empathy map | Design System",
    project_role_ux: "UX Designer",
    project_role_ui: "UI Designer",
    project_button_check: "Check project",
    about_me_footer_mobile: "Copyright 2025 - All Rights Reserved"
  },
  pt: {
    company: "DESIGNER DE PRODUTO",
    main_title_1: "Transformando complexidade em simplicidade e",
    main_title_2: "intuitividade.",
    main_description: "Com mais de 3 anos de experiência em produtos B2B, especializo-me em gerenciar todo o processo, desde a descoberta até a entrega, criando soluções digitais estratégicas e impactantes.",
    talk_to_me: "Fale comigo",
    resume: "Currículo",
    about_me_title: "Você pode me chamar de Gei",
    about_me_subtitle: "Sou Designer UX/UI",
    about_me_paragraph_1: "Com 4 anos de experiência em UX/UI Design, atuo na construção de soluções ponta a ponta para produtos B2B e B2C, desde a fase de pesquisa até a prototipação de alta fidelidade. Uso o Figma no meu dia a dia para criar e iterar interfaces intuitivas, sempre alinhadas aos objetivos do negócio.",
    about_me_paragraph_2: "Minha formação em Psicologia me levou a descobrir o design como uma forma de resolver problemas reais por meio da tecnologia — e é isso que me move. No meu tempo livre, gosto de conhecer novos lugares, marcar encontros tranquilos com amigos e ter boas conversas sem pressa.",
    about_me_psychology: "PSICOLOGIA",
    about_me_human_first: "Priorizando o humano",
    about_me_trips: "VIAGENS",
    about_me_footer: "Construindo soluções",
    project_title: "FluencyForge",
    project_tag_mobile: "Mobile",
    project_tag_teaching: "Educação",
    project_description: "Aplicativo focado em educação e aprendizado de novos idiomas. Explore os limites da fluência linguística com o FluencyForge: onde personalização encontra eficiência, moldando seu caminho rumo à maestria em idiomas.",
    project_card_screens_amount: "+50",
    project_card_components_amount: "+20",
    project_card_other_amount: "+20",
    project_card_screens: "Telas",
    project_card_components: "Componentes",
    project_card_other: "Outros",
    project_skills_title: "Habilidades aplicadas",
    project_skills_1: "Design thinking | Análise da concorrência | Pesquisa quantitativa",
    project_skills_2: "Pesquisa qualitativa | Prototipagem | Wireframe | Fluxo do usuário",
    project_skills_3: "Arquitetura da informação | Mapa de empatia | Design System",
    project_role_ux: "Designer UX",
    project_role_ui: "Designer UI",
    project_button_check: "Ver projeto",
    about_me_footer_mobile: "Copyright 2025 - Todos os Direitos Reservados"
  }
};
