const translations = {
  en: {
    company: "PRODUCT DESIGNER",
    hero_tagline: "Product Designer",
    hero_since: "Creating experiences since 2021",
    hero_intro: "Geissy but you can call me Gei",
    hero_cta: "Get to know me more",
    main_title_1: "Transforming complexity into simplicity and ",
    main_title_2: "intuitiveness.",
    main_description: "For more than 4 years, I’ve been creating purposeful solutions by understanding people and turning insights into meaningful experiences.",
    talk_to_me: "Talk to me",
    about_me_button: "Learn more",
    about_me_button_less: "Show less",
    resume: "Resume",
    about_me_title: "You can call me Gei",
    about_me_subtitle: "Product Designer",
    about_me_paragraph_1: "With 4 years of experience in UX/UI Design, I work on end-to-end solutions for B2B and B2C products — from research to high-fidelity prototyping. I use Figma daily to create and iterate on intuitive interfaces, always aligned with business goals.",
    about_me_paragraph_2: "My background in Psychology led me to discover design as a way to solve real problems through technology, and that’s what motivates me.",
    about_me_paragraph_3: "In my free time, I enjoy discovering new places, having relaxed meetups with friends, and savoring good conversations, without rush.",
    about_me_psychology: "PSYCHOLOGY",
    about_me_human_first: "Human-first",
    about_me_trips: "TRIPS",
    about_me_footer: "Building solutions",
    about_me_companies_label: "I created solutions for",
    about_me_companies_title: "Great companies",
    about_me_tools_title: "Main work tools",
    about_me_photo_flip_hint:
      "Portrait of Geissy — hover, tap, or press Enter to see the other side.",
    about_me_footer_description: "As a UX/UI Designer at Loomi, I contribute to digital products for leading clients such as:",
    project_title: "FluencyForge",
    project_tag_mobile: "Mobile",
    project_description: "App focused on education and learning new languages. Explore the boundaries of linguistic fluency with FluencyForge: where personalization meets efficiency, shaping your path to language mastery.",
    project_card_screens_amount: "30",
    project_card_components_amount: "15",
    project_card_other_amount: "3",
    project_card_screens: "Screens",
    project_card_components: "Components",
    project_card_other: "Month",
    project_skills_title: "Applied skills",
    project_skills_1: "Design thinking | Competitor analysis | Quantitative research",
    project_skills_2: "Qualitative research | Prototyping | Wireframe | User flow",
    project_skills_3: "Information architecture | Empathy map | Design System",
    project_role_ux: "UX Designer",
    project_role_ui: "UI Designer",
    project_button_check: "Check project",
    projects_eyebrow: "Explore my work",
    projects_heading_all: "All projects",
    projects_heading_web: "Web",
    projects_heading_mobile: "Mobile",
    projects_filter_all: "All Projects",
    projects_filter_web: "Web",
    projects_filter_mobile: "Mobile",
    projects_filter_aria: "Filter projects by platform",
    project_card_vivo_name: "Vivo+",
    project_card_vivo_subtitle_start: "Internal app for ",
    project_card_vivo_subtitle_brand: "Vivo",
    project_card_vivo_subtitle_end: " sellers",
    project_card_vivo_year: "2024",
    project_card_vivo_period: "Current",
    project_card_vivo_tag_tablet: "Tablet",
    project_card_vivo_tag_phone: "Cell phone",
    project_card_vivo_goal_label: "Contribution",
    project_card_vivo_goal_text: "I contributed to evolving the sales and customer service experience by designing digital solutions that simplify processes, support consultants' daily routines, and make operations more efficient.",
    project_spotlight_goal_label: "Goal",
    project_spotlight_user_label: "User",
    project_spotlight_features_label: "Main features",
    project_card_1_title: "BBEE - Smart apiculture",
    project_card_1_type: "Real project",
    project_card_1_year: "2023",
    project_card_bbee_goal_text: "Centralize beekeeping management in a single platform, enabling production tracking, goal setting, operations organization, and decision-making support.",
    project_card_bbee_user_text: "Beginner and experienced beekeepers who want to organize and track the management of their apiaries.",
    project_card_bbee_features_text: "The platform allows users to create and track production goals, manage tasks and collaborators, monitor apiary performance, and control the stock of supplies needed to carry out activities.",
    project_card_2_title: "FluencyForge",
    project_card_2_type: "Study project",
    project_card_2_year: "2024",
    project_card_fluency_period: "Study project",
    project_card_fluency_goal_text: "Make language learning more efficient through personalized study plans, AI-powered practice, and continuous progress tracking.",
    project_card_fluency_user_text: "People who want to learn a new language.",
    project_card_fluency_features_text: "Creation of personalized study paths, speaking and writing practice with AI, exercise and content generation, progress tracking, fluency tests, and study goals and reminder setup.",
    project_plat_web: "Web",
    project_plat_app: "App",
    experience_title: "Professional experience",
    experience_loomi_role: "Product Designer",
    experience_loomi_paragraph_1_start: "I work as a Product Designer for B2B and B2C products, handling multiple projects for clients such as ",
    experience_loomi_paragraph_1_highlight: "Neoenergia, Vivo, Vibe, Moura Dubeux, IT Forum, and Atvos.",
    experience_loomi_paragraph_1_end: " I lead end-to-end design cycles from discovery to delivery, addressing undefined problems, information architecture, and complex flows across desktop and mobile products.",
    experience_loomi_paragraph_2: "I maintain active communication with clients, focusing on understanding challenges and turning them into efficient digital solutions.",
    experience_loomi_recurring_title: "Recurring contributions",
    experience_loomi_item_1: "Structured discovery facilitation, aligning context, goals, and priorities with clients.",
    experience_loomi_item_2: "Process, journey, and flow mapping focused on operational efficiency and UX best practices.",
    experience_loomi_item_3: "Flow, wireframe, and prototype creation and validation supported by benchmarks, market analysis, and usability tests.",
    experience_loomi_item_4: "Production and presentation of strategic deliverables to support product decisions and solution evolution.",
    experience_loomi_period_from: "Jun 2024",
    experience_period_current: "Current",
    experience_sysvale_period_from: "Sep 2021",
    experience_sysvale_period_to: "Jun 2024",
    experience_sysvale_role: "UX/UI Designer",
    experience_sysvale_summary: "I worked as a UX/UI Designer creating end-to-end interfaces for healthcare products. Management systems committed to health outcomes.",
    experience_sysvale_paragraph_1: "In daily work, I designed new screens, shaped user experience, and created and documented Design System components to keep the product more organized, consistent, and scalable.",
    experience_sysvale_paragraph_2: "I also joined flow validations with clients and monitored user experience with tools such as FullStory, to better understand usage and identify improvement opportunities.",
    experience_sysvale_impact_number: "+ 2,091,488",
    experience_sysvale_impact_label: "PEOPLE IMPACTED",
    footer_copyright: "Copyright © Geissy Maysla, 2026",
    footer_name: "Geissy Maysla",
    footer_back_to_top: "Back to top",
    experience_button_more: "Show more",
    experience_button_less: "Show less",
    about_me_video_aria: "Watch introduction video",
    about_video_modal_title: "Introduction video",
    about_video_modal_close: "Close video",
  },
  pt: {
    company: "DESIGNER DE PRODUTO",
    hero_tagline: "Designer de Produto",
    hero_since: "Criando experiências desde 2021",
    hero_intro: "Geissy, mas pode me chamar de Gei",
    hero_cta: "Saiba mais sobre mim",
    main_title_1: "Transformando complexidade em simplicidade e ",
    main_title_2: "intuitividade.",
    main_description: " Há mais de 4 anos, venho criando soluções com propósito, entendendo as pessoas e transformando insights em experiências significativas.",
    talk_to_me: "Fale comigo",
    about_me_button: "Saiba mais",
    about_me_button_less: "Ver menos",
    resume: "Currículo",
    about_me_title: "Você pode me chamar de Gei",
    about_me_subtitle: "Product Designer",
    about_me_paragraph_1: "Criando experiências há mais de 4 anos como Product Designer, atuo na construção de soluções do discovery ao delivery. Utilizo algumas ferramentas no meu dia a dia para realizar essas entregas, como: Figma, NotebookLM, Lovable, Cursor, Miro, entre outras. O melhor resultado sempre será a entrega de valor para o cliente, alinhada aos objetivos do negócio, solucionando a dor real do usuário final.",
    about_me_paragraph_2: "Minha formação em Psicologia me levou a descobrir o design como uma forma de resolver problemas reais por meio da tecnologia, e isso é o que me motiva.",
    about_me_paragraph_3: "No meu tempo livre, gosto de conhecer novos lugares, ter encontros tranquilos com amigos e aproveitar boas conversas, sem pressa.",
    about_me_psychology: "PSYCHOLOGY",
    about_me_human_first: "Human-first",
    about_me_trips: "TRIPS",
    about_me_footer: "Construindo soluções",
    about_me_companies_label: "Criei soluções para",
    about_me_companies_title: "Grandes empresas",
    about_me_tools_title: "Principais ferramentas de trabalho",
    about_me_photo_flip_hint:
      "Retrato de Geissy — passe o mouse, toque ou pressione Enter para ver o verso.",
    about_me_footer_description: "Como UX/UI Designer na Loomi, contribuo para a criação de produtos digitais para grandes clientes como:",
    project_title: "FluencyForge",
    project_tag_mobile: "Mobile",
    project_description: "Aplicativo focado em educação e aprendizado de novos idiomas. Explore os limites da fluência linguística com o FluencyForge: onde personalização encontra eficiência, moldando seu caminho rumo à maestria em idiomas.",
    project_card_screens_amount: "30",
    project_card_components_amount: "15",
    project_card_other_amount: "3",
    project_card_screens: "Telas",
    project_card_components: "Componentes",
    project_card_other: "Meses",
    project_skills_title: "Habilidades aplicadas",
    project_skills_1: "Design thinking | Análise da concorrência | Pesquisa quantitativa",
    project_skills_2: "Pesquisa qualitativa | Prototipagem | Wireframe | Fluxo do usuário",
    project_skills_3: "Arquitetura da informação | Mapa de empatia | Design System",
    project_role_ux: "Designer UX",
    project_role_ui: "Designer UI",
    project_button_check: "Ver projeto",
    projects_eyebrow: "Explore meus trabalhos",
    projects_heading_all: "Todos os projetos",
    projects_heading_web: "Web",
    projects_heading_mobile: "Mobile",
    projects_filter_all: "Todos os projetos",
    projects_filter_web: "Web",
    projects_filter_mobile: "Mobile",
    projects_filter_aria: "Filtrar projetos por plataforma",
    project_card_vivo_name: "Vivo+",
    project_card_vivo_subtitle_start: "App interno para vendedores da ",
    project_card_vivo_subtitle_brand: "Vivo",
    project_card_vivo_subtitle_end: "",
    project_card_vivo_year: "2024",
    project_card_vivo_period: "Atual",
    project_card_vivo_tag_tablet: "Tablet",
    project_card_vivo_tag_phone: "Celular",
    project_card_vivo_goal_label: "Atuação",
    project_card_vivo_goal_text: "Contribuí para a evolução da experiência de vendas e atendimento por meio do desenho de soluções digitais que simplificam processos, apoiam a rotina dos consultores e tornam as operações mais eficientes.",
    project_spotlight_goal_label: "Objetivo",
    project_spotlight_user_label: "Usuário",
    project_spotlight_features_label: "Principais funcionalidades",
    project_card_1_title: "BBEE - Apicultura inteligente",
    project_card_1_type: "Projeto real",
    project_card_1_year: "2023",
    project_card_bbee_goal_text: "Centralizar a gestão apícola em uma única plataforma, permitindo o acompanhamento da produção, definição de metas, organização das operações e apoio à tomada de decisões.",
    project_card_bbee_user_text: "Apicultores iniciantes e experientes que desejam organizar e acompanhar a gestão de seus apiários.",
    project_card_bbee_features_text: "A plataforma permite criar e acompanhar metas de produção, gerenciar tarefas e colaboradores, monitorar o desempenho dos apiários e controlar o estoque de insumos necessários para a execução das atividades.",
    project_card_2_title: "FluencyForge",
    project_card_2_type: "Projeto de estudo",
    project_card_2_year: "2024",
    project_card_fluency_period: "Projeto de estudo",
    project_card_fluency_goal_text: "Tornar o aprendizado de idiomas mais eficiente por meio de planos de estudo personalizados, prática com IA e acompanhamento contínuo do progresso.",
    project_card_fluency_user_text: "Pessoas que desejam aprender um novo idioma.",
    project_card_fluency_features_text: "Criação de trilhas de estudo personalizadas, prática de fala e escrita com IA, geração de exercícios e conteúdos, acompanhamento do progresso, testes de fluência e configuração de metas e lembretes de estudo.",
    project_plat_web: "Web",
    project_plat_app: "App",
    experience_title: "Experiência profissional",
    experience_loomi_role: "Product Designer",
    experience_loomi_paragraph_1_start: "Atuo como Product Designer para produtos B2B e B2C, trabalhando em múltiplos projetos para clientes como ",
    experience_loomi_paragraph_1_highlight: "Neoenergia, Vivo, Vibe, Moura Dubeux, IT Forum e Atvos.",
    experience_loomi_paragraph_1_end: " Conduzo ciclos completos de design, do discovery ao delivery, lidando com problemas pouco definidos, organização de informações e fluxos complexos em produtos desktop e mobile.",
    experience_loomi_paragraph_2: "Comunicação ativa com clientes, focada em entender desafios e transformar em soluções digitais eficientes.",
    experience_loomi_recurring_title: "Atuação recorrente",
    experience_loomi_item_1: "Condução de Discovery estruturado, alinhando contexto, objetivos e prioridades junto aos clientes.",
    experience_loomi_item_2: "Mapeamento de processos, jornadas e fluxos, com foco em eficiência operacional e boas práticas de UX.",
    experience_loomi_item_3: "Criação e validação de fluxos, wireframes e protótipos, apoiados por benchmarks, análises de mercado e testes de usabilidade.",
    experience_loomi_item_4: "Produção e apresentação de entregáveis estratégicos, apoiando decisões de produto e evolução das soluções.",
    experience_loomi_period_from: "Jun de 2024",
    experience_period_current: "Atualmente",
    experience_sysvale_period_from: "Set de 2021",
    experience_sysvale_period_to: "Jun de 2024",
    experience_sysvale_role: "UX/UI Designer",
    experience_sysvale_summary: "Atuei como UX/UI Designer criando interfaces de ponta a ponta para produtos na área da saúde. Sistemas de gestão com compromisso com a saúde.",
    experience_sysvale_paragraph_1: "No dia a dia, desenvolvia novas telas, pensava na experiência do usuário e também criava e documentava componentes para o Design System, ajudando a manter tudo mais organizado, consistente e escalável.",
    experience_sysvale_paragraph_2: "Participava de validações dos fluxos junto aos clientes e acompanhava a experiência dos usuários com ferramentas como o FullStory, buscando entender melhor a experiência e identificar oportunidades de melhoria.",
    experience_sysvale_impact_number: "+ 2.091.488",
    experience_sysvale_impact_label: "PESSOAS IMPACTADAS",
    footer_copyright: "Copyright © Geissy Maysla, 2026",
    footer_name: "Geissy Maysla",
    footer_back_to_top: "Voltar ao topo",
    experience_button_more: "Mostrar mais",
    experience_button_less: "Mostrar menos",
    about_me_video_aria: "Assistir vídeo de apresentação",
    about_video_modal_title: "Vídeo de apresentação",
    about_video_modal_close: "Fechar vídeo",
  }
};
